# Generated by Django 4.2.2 on 2023-06-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.ImageField(upload_to='')),
                ('person2', models.ImageField(upload_to='')),
                ('height1', models.IntegerField()),
                ('height2', models.IntegerField()),
            ],
        ),
    ]
