# Generated by Django 4.2.2 on 2023-06-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='height1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='height2',
            field=models.FloatField(),
        ),
    ]
