# Generated by Django 4.2.2 on 2023-07-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_data_final_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='final_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
