# Generated by Django 4.2.2 on 2023-07-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_data_final_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='final_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='data',
            name='person1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='data',
            name='person2',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
